import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import NavBar from "@/components/Nav/NavBar";

export const metadata: Metadata = {
  title: "PlanPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <NavBar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
